# Generated by Django 2.0.5 on 2018-05-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionAuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
